spring:
  application:
    name: beiSenDemo
  data:
    redis:
      port: 6379
      host: localhost
      password:
  datasource:
    url: jdbc:mysql://localhost:3306/${database.name}?useUnicode=true&allowPublicKeyRetrieval=true&autoReconnect=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123321

# mybatis 相关统一配置
mybatis-plus:
  configuration:
    #开启下划线转驼峰
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/**/*.xml


# 默认的数据库名
database:
  name: bei_Sen_Demo

# 安全配置
security:
  salt: tech_π # 密码加盐, 更安全的做法是每个用户的密码使用独立的盐，并将其保存在用户表中
  salt-index: 3 # 盐插入的位置

paicoding:
  sensitive: # 敏感词校验相关配置
    enable: true
    deny: # 自定义的敏感词，英文逗号分割
    allow: 国,制作,码,亚洲,中国,公司,简历,性,国研,鬼,国庆,用户,扑克,法,鲁迅,祖国,口,色,俄罗斯 # 自定义的非敏感词，英文逗号分割
  jwt:
    issuer: beiSen_demo # 签发者
    secret: hello_world # 签名密钥
    expire: 432000000 # jwt的有效期，默认30天